import { HeaderNav } from "@/app/components/HeaderNav.client";
import Image from "next/image";
import "./page.css";

const directions = [["Строительство", "Новые автомагистрали и обходы"], ["Эксплуатация", "Содержание и безопасность дорог"], ["Инвестиции", "Концессии и инфраструктурные проекты"], ["Цифровые сервисы", "ИТС, оплата и пользовательские продукты"], ["Придорожная инфраструктура", "МФЗ, АЗС и сервисные зоны"], ["Международное сотрудничество", "Партнёрские и отраслевые проекты"]] as const;
const compliance = ["Раскрытие информации", "Инсайдерам", "Антимонопольный комплаенс", "Отозванные доверенности", "Нормативно-правовая документация"] as const;
function Card({ title, text }: Readonly<{ title: string; text?: string }>) { return <a className="about-card" href="#contacts"><span><strong>{title}</strong>{text && <small>{text}</small>}</span><b aria-hidden="true">→</b></a>; }
export default function Page() { return <><header className="site-header"><HeaderNav /></header><div id="header-scroll-sentinel" className="header-scroll-sentinel" aria-hidden="true" /><main id="main-content" className="about-page" tabIndex={-1}>
  <section className="about-hero" aria-labelledby="about-title"><div><p className="about-crumbs">Главная / О Компании</p><h1 id="about-title">О Компании</h1><p className="about-lead">Мы создаём современную дорожную инфраструктуру,<br />которая объединяет регионы и открывает возможности.</p><div className="about-mission"><b>МИССИЯ</b><p>Безопасные дороги, развитие территорий<br />и комфорт пользователей.</p></div></div><div className="about-quote">ЦИТАТА / ФОТО</div></section>
  <section className="about-section about-history" aria-labelledby="history"><h2 id="history">История Автодора</h2><p className="about-subtitle">Развитие дорожной сети по годам</p><div className="about-map"><Image src="/media/about-history-map.png" alt="Карта развития дорожной сети Автодора" fill sizes="(max-width: 800px) 100vw, 1464px" /><div className="about-years"><span>2018</span><span>2020</span><span>2022</span><span>2024</span><strong>2026</strong></div></div></section>
  <section className="about-section" aria-labelledby="directions"><h2 id="directions">Направления деятельности</h2><p className="about-subtitle">Основные направления представлены одновременно и ведут в профильные разделы</p><div className="about-grid about-directions">{directions.map(([title, text]) => <Card key={title} title={title} text={text} />)}</div></section>
  <section className="about-section" aria-labelledby="structure"><h2 id="structure">Структура ГК</h2><p className="about-subtitle">Переход к структуре дочерних обществ и филиалов</p><div className="about-grid about-structure"><Card title="Дочерние общества" text="Компании группы и направления работы" /><Card title="Филиалы" text="Региональная структура Государственной компании" /></div></section>
  <section className="about-section" aria-labelledby="comp"><h2 id="comp">Комплаенс</h2><p className="about-subtitle">Документы и обязательное раскрытие информации</p><div className="about-grid about-compliance">{compliance.map(title => <Card key={title} title={title} />)}</div></section>
  <section id="contacts" className="about-section about-contacts" aria-labelledby="contacts"><h2 id="contacts">Контакты</h2><div className="about-contact-layout"><address><b>Государственная компания</b><strong>ГК «Автодор»</strong><p>Москва, Страстной бульвар, 9<br /><a href="tel:+74957271195">+7 495 727-11-95</a><br /><a href="mailto:info@russianhighways.ru">info@russianhighways.ru</a></p><a className="about-contact-button" href="https://russianhighways.ru/about/contacts/">Все контакты</a></address><div className="about-contact-map">КАРТА / АДРЕСА</div></div></section>
</main><footer className="site-footer" data-section="footer"><div className="footer-frame"><p className="footer-copyright">© 2009–2026 Государственная компания «Российские автомобильные дороги»</p></div></footer></>; }
